import {
  ArrowLeft,
  Download,
  FileText,
  Printer,
  CheckCircle2,
  AlertTriangle,
  ShieldCheck,
  UserCheck,
  CalendarDays,
  MapPin,
  Package,
  Search,
} from "lucide-react";

import { useNavigate } from "react-router-dom";

function Report() {
  const navigate = useNavigate();

  return (
    <div className="p-8">

      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <button
            onClick={() => navigate("/evidence-review")}
            className="flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600 mb-3"
          >
            <ArrowLeft size={17} />
            Back to Evidence Review
          </button>

          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-xl bg-blue-100 flex items-center justify-center">
              <FileText className="text-blue-600" size={23} />
            </div>

            <div>
              <h1 className="text-2xl font-bold text-slate-900">
                Inspection Report
              </h1>

              <p className="text-sm text-slate-500 mt-1">
                Official inspection record generated by Metra-X
              </p>
            </div>
          </div>
        </div>

        {/* Report ID */}
        <div className="text-right">
          <p className="text-xs text-slate-400 uppercase tracking-wide">
            Report ID
          </p>

          <p className="font-semibold text-slate-800">
            MTX-RPT-2026-00128
          </p>
        </div>
      </div>


      {/* Final Status */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <div className="flex items-center justify-between">

          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-full bg-amber-100 flex items-center justify-center">
              <AlertTriangle
                size={28}
                className="text-amber-600"
              />
            </div>

            <div>
              <p className="text-sm text-slate-500">
                Final Inspection Assessment
              </p>

              <h2 className="text-xl font-bold text-amber-600 mt-1">
                Potential Violation Confirmed
              </h2>

              <p className="text-sm text-slate-500 mt-1">
                Finalized after inspector verification
              </p>
            </div>
          </div>

          <div className="flex gap-3">

            <button
              className="flex items-center gap-2 px-4 py-2.5 border border-slate-200 rounded-xl text-sm font-medium text-slate-700 hover:bg-slate-50"
            >
              <Printer size={17} />
              Print
            </button>

            <button
              className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-medium hover:bg-blue-700"
            >
              <Download size={17} />
              Download PDF
            </button>

          </div>

        </div>
      </div>


      {/* Product Information */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <div className="flex items-center gap-2 mb-5">
          <Package size={20} className="text-blue-600" />

          <h2 className="font-bold text-lg text-slate-900">
            Product Information
          </h2>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-3 gap-6">

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Product Name
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              Premium Basmati Rice
            </p>
          </div>

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Brand
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              Example Foods
            </p>
          </div>

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Category
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              Food & Beverages
            </p>
          </div>

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Net Quantity
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              1 kg
            </p>
          </div>

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Declared MRP
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              ₹180
            </p>
          </div>

          <div>
            <p className="text-xs text-slate-400 uppercase">
              Inspection ID
            </p>

            <p className="font-semibold text-slate-800 mt-1">
              MTX-2026-00128
            </p>
          </div>

        </div>
      </div>


      {/* Inspection Details */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <h2 className="font-bold text-lg text-slate-900 mb-5">
          Inspection Details
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">

          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center">
              <CalendarDays size={19} className="text-blue-600" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Inspection Date
              </p>

              <p className="text-sm font-semibold text-slate-800">
                26 August 2026
              </p>
            </div>
          </div>


          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center">
              <UserCheck size={19} className="text-blue-600" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Inspector
              </p>

              <p className="text-sm font-semibold text-slate-800">
                Enforcement Officer
              </p>
            </div>
          </div>


          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center">
              <MapPin size={19} className="text-blue-600" />
            </div>

            <div>
              <p className="text-xs text-slate-400">
                Inspection Location
              </p>

              <p className="text-sm font-semibold text-slate-800">
                Retail Inspection
              </p>
            </div>
          </div>

        </div>
      </div>


      {/* Findings */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <div className="flex items-center gap-2 mb-5">
          <Search size={20} className="text-blue-600" />

          <h2 className="font-bold text-lg text-slate-900">
            Compliance Findings
          </h2>
        </div>


        <div className="space-y-4">

          {/* Verified */}
          <div className="border border-green-200 bg-green-50 rounded-xl p-4">

            <div className="flex items-start justify-between">

              <div className="flex gap-3">
                <CheckCircle2
                  size={21}
                  className="text-green-600 mt-0.5"
                />

                <div>
                  <h3 className="font-semibold text-slate-900">
                    Net Quantity Declaration
                  </h3>

                  <p className="text-sm text-slate-600 mt-1">
                    Declaration detected and verified successfully.
                  </p>
                </div>
              </div>

              <span className="text-xs font-semibold text-green-700 bg-green-100 px-3 py-1 rounded-full">
                VERIFIED
              </span>

            </div>

          </div>


          {/* Violation */}
          <div className="border border-red-200 bg-red-50 rounded-xl p-4">

            <div className="flex items-start justify-between">

              <div className="flex gap-3">
                <AlertTriangle
                  size={21}
                  className="text-red-600 mt-0.5"
                />

                <div>
                  <h3 className="font-semibold text-slate-900">
                    MRP Declaration
                  </h3>

                  <p className="text-sm text-slate-600 mt-1">
                    Potential non-compliance detected in the
                    declaration.
                  </p>

                  <p className="text-xs text-slate-500 mt-2">
                    AI confidence: 84%
                  </p>
                </div>
              </div>

              <span className="text-xs font-semibold text-red-700 bg-red-100 px-3 py-1 rounded-full">
                CONFIRMED
              </span>

            </div>

          </div>


          {/* Manufacturer */}
          <div className="border border-slate-200 bg-slate-50 rounded-xl p-4">

            <div className="flex items-start justify-between">

              <div className="flex gap-3">
                <ShieldCheck
                  size={21}
                  className="text-slate-500 mt-0.5"
                />

                <div>
                  <h3 className="font-semibold text-slate-900">
                    Manufacturer Declaration
                  </h3>

                  <p className="text-sm text-slate-600 mt-1">
                    Declaration requires additional verification.
                  </p>
                </div>
              </div>

              <span className="text-xs font-semibold text-slate-600 bg-slate-200 px-3 py-1 rounded-full">
                REVIEWED
              </span>

            </div>

          </div>

        </div>
      </div>


      {/* Evidence */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <h2 className="font-bold text-lg text-slate-900 mb-5">
          Inspection Evidence
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

          <div className="h-64 bg-slate-100 rounded-xl border border-slate-200 flex items-center justify-center">

            <div className="text-center">
              <Package
                size={42}
                className="mx-auto text-slate-400 mb-3"
              />

              <p className="font-medium text-slate-600">
                Package Image
              </p>

              <p className="text-xs text-slate-400 mt-1">
                Evidence image preview
              </p>
            </div>

          </div>


          <div className="space-y-4">

            <div className="p-4 bg-red-50 border border-red-200 rounded-xl">

              <p className="text-xs font-semibold text-red-600 uppercase">
                Highlighted Evidence
              </p>

              <p className="font-semibold text-slate-900 mt-2">
                MRP Declaration
              </p>

              <p className="text-sm text-slate-600 mt-1">
                The highlighted region was reviewed by the
                inspector before finalization.
              </p>

            </div>

            <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl">

              <p className="text-xs font-semibold text-blue-600 uppercase">
                Rule Reference
              </p>

              <p className="text-sm text-slate-700 mt-2">
                Applicable packaged commodity declaration
                requirement.
              </p>

              <p className="text-xs text-slate-500 mt-2">
                Rule version and amendment must be recorded
                with the final enforcement record.
              </p>

            </div>

          </div>

        </div>
      </div>


      {/* Inspector Verification */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-6 shadow-sm">

        <div className="flex items-center gap-3 mb-5">

          <div className="w-10 h-10 rounded-lg bg-green-100 flex items-center justify-center">
            <UserCheck
              size={20}
              className="text-green-600"
            />
          </div>

          <div>
            <h2 className="font-bold text-lg text-slate-900">
              Inspector Verification
            </h2>

            <p className="text-sm text-slate-500">
              Final decision recorded by authorized officer
            </p>
          </div>

        </div>


        <div className="bg-slate-50 rounded-xl p-4">

          <div className="flex items-center justify-between">

            <div>
              <p className="text-xs text-slate-400 uppercase">
                Decision
              </p>

              <p className="font-semibold text-slate-800 mt-1">
                Potential Violation Confirmed
              </p>
            </div>

            <div className="text-right">

              <p className="text-xs text-slate-400 uppercase">
                Verified By
              </p>

              <p className="font-semibold text-slate-800 mt-1">
                Enforcement Officer
              </p>

            </div>

          </div>

        </div>

      </div>


      {/* Bottom Actions */}
      <div className="flex justify-between items-center pb-8">

        <button
          onClick={() => navigate("/new-inspection")}
          className="px-5 py-3 border border-slate-200 rounded-xl text-sm font-medium text-slate-700 hover:bg-slate-50"
        >
          Start New Inspection
        </button>


        <div className="flex gap-3">

          <button
            className="flex items-center gap-2 px-5 py-3 border border-slate-200 rounded-xl text-sm font-medium text-slate-700 hover:bg-slate-50"
          >
            <FileText size={17} />
            Export Editable
          </button>

          <button
            className="flex items-center gap-2 px-5 py-3 bg-blue-600 text-white rounded-xl text-sm font-medium hover:bg-blue-700"
          >
            <Download size={17} />
            Download Report
          </button>

        </div>

      </div>


      {/* Disclaimer */}
      <div className="border-t border-slate-200 pt-5 pb-4">

        <p className="text-xs text-slate-400 text-center">
          Metra-X provides AI-assisted compliance analysis.
          Final legal decisions and enforcement actions remain
          the responsibility of the authorized enforcement
          authority.
        </p>

      </div>

    </div>
  );
}

export default Report;